const invoke = <T = any>(channel: string, ...args: unknown[]): Promise<T> => {
  if (!window.clinic) {
    return Promise.reject(new Error('Clinic desktop API is unavailable. Run inside Electron.'))
  }
  return window.clinic.invoke(channel, ...args)
}

export const api = {
  getSettings: () => invoke('settings:get'),
  saveSettings: (settings: unknown) => invoke('settings:save', settings),
  listPrintTemplates: () => invoke('templates:list'),
  getPrintTemplate: (id: number) => invoke('templates:get', id),
  getActivePrintTemplate: () => invoke('templates:active'),
  savePrintTemplate: (input: unknown) => invoke('templates:save', input),
  setActivePrintTemplate: (id: number) => invoke('templates:setActive', id),
  deletePrintTemplate: (id: number) => invoke('templates:delete', id),
  pickLetterheadFile: () => invoke('templates:pickFile'),
  letterheadPreview: (fileName: string, fileKind: 'pdf' | 'image' | 'word' | null) =>
    invoke('templates:preview', fileName, fileKind),
  pickBillTemplateFile: () => invoke('templates:pickBillFile'),
  billTemplatePreview: (fileName: string, fileKind: 'pdf' | 'image' | 'word' | null) =>
    invoke('templates:billPreview', fileName, fileKind),
  clearBillTemplateFile: (fileName: string | null) => invoke('templates:clearBillFile', fileName),
  getDashboard: () => invoke('dashboard:get'),
  getReports: (input?: { from?: string; to?: string }) => invoke('reports:get', input),
  exportReport: (kind: 'patients' | 'visits' | 'prescriptions' | 'bills' | 'payments' | 'tests', from: string, to: string) =>
    invoke('reports:export', kind, from, to),
  globalSearch: (query: string) => invoke('search:global', query),
  listPatients: (query = '') => invoke('patients:list', query),
  getPatient: (id: number) => invoke('patients:get', id),
  findDuplicates: (input: unknown) => invoke('patients:duplicates', input),
  createPatient: (input: unknown) => invoke('patients:create', input),
  updatePatient: (id: number, input: unknown) => invoke('patients:update', id, input),
  archivePatient: (id: number) => invoke('patients:archive', id),
  patientDashboard: (id: number) => invoke('patients:dashboard', id),
  listVisits: (query = '') => invoke('visits:list', query),
  listPrescriptions: (query = '') => invoke('prescriptions:list', query),
  listBills: (query = '') => invoke('bills:list', query),
  listPayments: (query = '') => invoke('payments:list', query),
  getVisit: (id: number) => invoke('visits:get', id),
  createVisit: (input: unknown) => invoke('visits:create', input),
  updateVisit: (id: number, input: unknown) => invoke('visits:update', id, input),
  deleteVisit: (id: number) => invoke('visits:delete', id),
  getVitals: (id: number) => invoke('visits:vitals', id),
  printVisit: (id: number) => invoke('visits:print', id),
  setVisitTests: (visitId: number, items: unknown) => invoke('visits:setTests', visitId, items),
  setVisitProcedures: (visitId: number, items: unknown) =>
    invoke('visits:setProcedures', visitId, items),
  getVisitTests: (visitId: number) => invoke('visits:getTests', visitId),
  getVisitProcedures: (visitId: number) => invoke('visits:getProcedures', visitId),
  getVisitLeftoverBillItems: (visitId: number) => invoke('visits:leftoverBillItems', visitId),
  getVisitBillingSummary: (visitId: number) => invoke('visits:billingSummary', visitId),
  isVisitTestPaid: (id: number) => invoke('tests:isPaid', id),
  refundVisitTest: (id: number) => invoke('tests:refund', id),
  isVisitProcedurePaid: (id: number) => invoke('procedures:isPaid', id),
  refundVisitProcedure: (id: number) => invoke('procedures:refund', id),
  searchSymptoms: (query = '') => invoke('symptoms:search', query),
  listAllTests: (query = '') => invoke('tests:listAll', query),
  updateTestResult: (id: number, input: unknown) => invoke('tests:updateResult', id, input),
  scheduleTest: (id: number, scheduledAt: string) => invoke('tests:schedule', id, scheduledAt),
  setTestWorkflowStatus: (id: number, status: 'Completed' | 'Cancelled') =>
    invoke('tests:setWorkflowStatus', id, status),
  uploadTestReport: (id: number) => invoke('tests:uploadReport', id),
  openTestReport: (id: number) => invoke('tests:openReport', id),
  listOptions: (category: 'dosage_form' | 'frequency' | 'timing') => invoke('options:list', category),
  addOption: (category: 'dosage_form' | 'frequency' | 'timing', name: string) =>
    invoke('options:add', category, name),
  updateOption: (id: number, name: string) => invoke('options:update', id, name),
  deleteOption: (id: number) => invoke('options:delete', id),
  searchMedicines: (query: string) => invoke('medicines:search', query),
  listMedicines: (query = '') => invoke('medicines:list', query),
  createMedicine: (input: unknown) => invoke('medicines:create', input),
  updateMedicine: (id: number, input: unknown) => invoke('medicines:update', id, input),
  deactivateMedicine: (id: number) => invoke('medicines:deactivate', id),
  getPrescriptionByVisit: (visitId: number) => invoke('prescriptions:getByVisit', visitId),
  savePrescription: (input: unknown) => invoke('prescriptions:save', input),
  printPrescription: (visitId: number) => invoke('prescriptions:print', visitId),
  pdfPrescription: (visitId: number) => invoke('prescriptions:pdf', visitId),
  listTests: (query = '') => invoke('tests:list', query),
  upsertTest: (input: unknown) => invoke('tests:upsert', input),
  listProcedures: (query = '') => invoke('procedures:list', query),
  upsertProcedure: (input: unknown) => invoke('procedures:upsert', input),
  getBill: (id: number) => invoke('bills:get', id),
  listBillsForVisit: (visitId: number) => invoke('bills:getByVisit', visitId),
  saveBill: (input: unknown) => invoke('bills:save', input),
  cancelBill: (id: number) => invoke('bills:cancel', id),
  recordPayment: (input: unknown) => invoke('bills:pay', input),
  listInvoicesForBill: (billId: number) => invoke('invoices:listByBill', billId),
  getInvoice: (id: number) => invoke('invoices:get', id),
  printInvoice: (id: number) => invoke('invoices:print', id),
  pdfInvoice: (id: number) => invoke('invoices:pdf', id),
  printBill: (id: number) => invoke('bills:print', id),
  pdfBill: (id: number) => invoke('bills:pdf', id),
  createBackup: () => invoke('backup:create'),
  restoreBackup: () => invoke('backup:restore'),
  getPaths: () => invoke('app:paths'),
  openPath: (p: string) => invoke('app:openPath', p),
  getAppInfo: () => invoke('app:info'),
  changeDataDir: () => invoke('app:changeDataDir'),
}
